---
# Configure docker

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ docker_services_enable }}"
  when: docker_enable_service
