---
# Install docker packages

- name: unwanted packages are removed
  package:
    name: "{{ docker_packages_remove }}"
    state: absent
  become: true
  when: docker_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ docker_packages_repos }}"
    state: present
  become: true

- name: prereq packages are installed
  package:
    name: "{{ docker_packages_prereq }}"
    state: present
  become: true

- name: packages are installed
  package:
    name: "{{ docker_packages_install }}"
    state: present
  become: true
